spring:  profiles:    active:    - uat# JASYPT CONFIGjasypt:  encryptor:    algorithm: PBEWithMD5AndDES    password: test@123    keyObtentionIterations: 1000    poolSize: 1    providerName: SunJCE    saltGeneratorClassname: org.jasypt.salt.RandomSaltGenerator    stringOutputType: base64
---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: http://mygitprofile/configserver-dev.git
          username: ENC(jasyptencryptedtext)
          password: ENC(jasyptencryptedtext)
          search-paths:
          - dev*logging:  path: /home/me/logs/configserver-dev  level:    com.fullerton.configserver: debug    org.springframework.web: debug---spring:  profiles: uat  cloud:    config:      server:        git:          uri: http://mygitprofile/config-server-uat.git          username: ENC(jasyptencryptedtext)          password: ENC(jasyptencryptedtext)          search-paths:          - uat*logging:  path: /home/me/logs/configserver-uat  level:    com.fullerton.configserver: info    org.springframework.web: info---spring:  profiles: prod  cloud:    config:      server:        git:          uri: http://mygitprofile/config-server-prod.git          username: ENC(jasyptencryptedtext)          password: ENC(jasyptencryptedtext)          search-paths:          - uat*logging:  path: /home/me/logs/configserver  level:    com.fullerton.configserver: info    org.springframework.web: info